name: Validate locations.json

on:
  push:
    branches:
      - main
    paths:
      - locations.json
    
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_JSONS: locations.json