name: Validate locations.json

on:
  push:
    branches:
      - main
    paths:
      - locations.json

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
        with:
          files: locations.json